### ISSUE TITLE
macOS Sierra 10.12.2 中存在无法记住登陆状态的问题

### ISSUE THREAD

**Issue by Renlong-Yin** [shanzi/diumoo#9]
从最初的 10.12 到 10.12.2 beta 已验证一直存在此问题，表现为每次退出 diumoo 应用后重新打开，皆需要重新登陆豆瓣账号。

望修复

**Comment by AnakinMac** [comment]
已经注意到这个问题了。。。会找时间看一下的。。。

**Comment by shanzi** [comment]
在中国大陆以外使用 diumoo 好像是无法记录登陆状态的，因为 douban 对于境外登陆做了特别屏蔽

不知道是不是属于这种情况

**Comment by Renlong-Yin** [comment]
@shanzi 确实为境外登陆。请问是否有方法绕过此限制？

**Comment by shanzi** [comment]
其实问题的原因是豆瓣对于境外IP转接到一个提示页面，导致 diumoo
无法判断你是否登陆成功了。但是每次登陆因为是直接走的登陆的API，所以在境外可以通过直接登录使用，但是没法记录登录状态。

这个问题好像没有什么特别好的解决方案，毕竟豆瓣自己是不支持在大陆以外使用的。

**Comment by AnakinMac** [comment]
我觉得还是可以治疗的。。。因为那个页面其实我们也就是要 uid 之类的信息。。。这种还是有其他方法可以获得的。。。

**Comment by shanzi** [comment]
可以研究一下。。。

**Comment by AnakinMac** [comment]
Hi All,

Latest beta https://dl.dropboxusercontent.com/u/3482430/diumoo_1.6b.zip should fixed the login issue.

Try it and report any issue you encounter.

Best
~Anakin
